# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Release

on:
  #  push:
  #    branches: [ "main" ]
  #    pull_request:
  #      branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
  release:
    types: [ created ]

jobs:
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
          cache-dependency-path: | # optional
            *.gradle*
            **/gradle-wrapper.properties

      - name: Gradle Build started
        run: ./gradlew clean windowsZip --no-daemon

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-window
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload Release to Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Releases
          path: |
            **/build/libs/*.jar
            **/build/distributions/*.zip

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: "Junit Windows Test Report"
          report_paths: '**/build/test-results/test/TEST-*.xml'

        # upload to release to tag
      - name: Update Release to Github Releses
        uses: softprops/action-gh-release@v2
        # only if this is exectued on tag/release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/libs/*.jar
            build/distributions/*.zip
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
